### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by fitrah9ramadhan** [MichaelStott/DataframeGUIKivy#2]
Hi! I am very interested in using your code, but when I run demo.py, I get the following error:

 Traceback (most recent call last):
   File "D:\PandasDataframeGUIKivy\dfguik.py", line 25, in <module>
     from kivy.garden.matplotlib.backend_kivyagg import FigureCanvas,\
   File "C:\Users\HP\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\garden\__init__.py", line 180, in load_module
     return self._load_module(fullname, moddir)
   File "C:\Users\HP\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\garden\__init__.py", line 183, in _load_module
     mod = imp.load_module(fullname, None, moddir,
   File "C:\Users\HP\AppData\Local\Programs\Python\Python38-32\lib\imp.py", line 244, in load_module
     return load_package(name, filename)
   File "C:\Users\HP\AppData\Local\Programs\Python\Python38-32\lib\imp.py", line 216, in load_package
     return _load(spec)
   File "C:\Users\HP\.kivy\garden\garden.matplotlib\__init__.py", line 1, in <module>
     from kivy.garden.matplotlib.backend_kivy import FigureCanvasKivy,\
   File "C:\Users\HP\.kivy\garden\garden.matplotlib\backend_kivy.py", line 256, in <module>
     from matplotlib import _png
 ImportError: cannot import name '_png' from 'matplotlib' (C:\Users\HP\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\__init__.py)

**Comment by jefpadfi** [comment]
I just found this great library for Kivy. I just spent the past few hours trying to fix the same issue. The newest version of matplotlib does not have _png any longer. I'm not sure what version of matplotlib was used when this library was created. Though here are the following edits I have created to get the entire program to work once again.

* matplotlib _png is no longer needed and import can be removed in backend_kivy.py of garden.matplotlib (you will have to manually install the kivy garden into your project or edit the source files that you reference to with the garden install command you used.

* inside dfguik.py the import for NavigationToolbar2Kivy is wrong as well. It is in backend_kivy not backend_kivyagg. This will need to be changed as well. Correct imports look as follows (line 25 originally)

original import statement
```
from kivy.garden.matplotlib.backend_kivyagg import FigureCanvas,\
                                                   NavigationToolbar2Kivy
```

correct import statement
```
# from garden.matplotlib.backend_kivyagg import FigureCanvas
from garden.matplotlib.backend_kivy import NavigationToolbar2Kivy
```

The FigureCanvase import is never used. I'm still going through to clean up the imports as there are many not used or needed at all.

* pandas.DataFrame.from_items was deprecated since [version 0.23.0](https://github.com/pandas-dev/pandas/blob/v0.23.4/pandas/core/frame.py#L1422-L1507) and needs to be changed to the following. (this is in demo.py line 26 for me)
```
return pd.DataFrame.from_dict({
        "Date": random_dates,
        "UserID": choice(*user_ids),
        "ProductID": choice(*product_ids),
        "IntColumn": choice(1, 2, 3),
        "FloatColumn": choice(np.nan, 1.0, 2.0, 3.0),
        "StringColumn": choice("A", "B", "C"),
        "Gaussian 1": np.random.normal(0, 1, size),
        "Gaussian 2": np.random.normal(0, 1, size),
        "Uniform": np.random.uniform(0, 1, size),
        "Binomial": np.random.binomial(20, 0.1, size),
        "Poisson": np.random.poisson(1.0, size),
    })
```

* Lastly I changed the matplotlib.use to the following that is in dfguik.py. Though i beleive this one is more for myself due to how i have the garden matplotlib installed on my source.
`matplotlib.use('module://garden.matplotlib.backend_kivy')`

Hope this helps. I'm submitting a pull request to get this repository updated and working again with the current as this is a great library which I like more than the garden-graph option.

* Lastly there is a warning for _init_toolbar method. Which was deprecated in Matplotlib 3.3 though it seems for now it still works until they fully remove it. So for now, I'm not worried about it.

**Comment by Anassoumi** [comment]
'matplotlib _png is no longer needed and import can be removed in backend_kivy.py of garden.matplotlib (you will have to manually install the kivy garden into your project or edit the source files that you reference to with the garden install command you used.'

Can you clarify how please ?
